[package]
name = "omnidesk-desktop"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
omnidesk-core = { path = "../omnidesk-core" }
font8x8 = "0.3.1"
accesskit = "0.25.1"

[target.'cfg(windows)'.dependencies]
winit = "0.30"
softbuffer = "0.4.8"
accesskit_winit = { version = "0.34.0", default-features = false, features = ["rwh_06"] }

[lints]
workspace = true
