[package]
name = "omnidesk-desktop"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
omnidesk-core = { path = "../omnidesk-core" }

[target.'cfg(windows)'.dependencies]
winit = "0.30"

[lints]
workspace = true
